name: Publish to NuGet

on:
  push:
    tags:
      - "v*.*.*" # e.g., v0.1.0

jobs:
  build-pack-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore StreamableNet.sln

      - name: Build
        run: dotnet build StreamableNet.sln -c Release --no-restore

      - name: Extract version from tag
        id: get_version
        run: |
          # tag format v0.1.0 -> 0.1.0
          echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Pack
        run: dotnet pack StreamableNet.csproj -c Release -o ./artifacts /p:PackageVersion=${{ steps.get_version.outputs.version }} --no-build

      - name: Publish to NuGet
        run: dotnet nuget push "./artifacts/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
